const swaggerJsdoc = require('swagger-jsdoc');
const options = {
  // List of files to be processed.
  apis: ['./routes/index.js'],

  basePath: '/',
  swaggerDefinition: {
    info: {
      description: 'Test API with autogenerated swagger doc',
      swagger: '2.0',
      title: 'Whatsapp API',
      version: '1.0.0',
    },
  },
};
const specs = swaggerJsdoc(options);
export default specs;
